-- Baseline schema: company, app_user, job, review, refresh_token.
-- Matches the tables Hibernate's ddl-auto=create-drop was generating from the
-- current @Entity classes. From here on, schema changes go in new Vn files,
-- never edits to this one.

create table company (
    id bigint generated by default as identity primary key,
    company_name varchar(255),
    location varchar(255),
    description varchar(255)
);

create table app_user (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password_hash varchar(255),
    full_name varchar(255),
    role varchar(255) check (role in ('APPLICANT','COMPANY','ADMIN')),
    auth_provider varchar(255) check (auth_provider in ('LOCAL','GOOGLE','GITHUB')),
    created_at timestamp(6) with time zone,
    company_id bigint references company
);

create table job (
    id bigint generated by default as identity primary key,
    title varchar(255),
    description varchar(255),
    location varchar(255),
    min_salary numeric(38,2),
    max_salary numeric(38,2),
    status smallint check (status between 0 and 2),
    posted_by bigint,
    company_id bigint references company
);

create table review (
    id bigint generated by default as identity primary key,
    title varchar(255),
    description varchar(255),
    rating float(53) not null,
    reviewed_by bigint,
    company_id bigint references company
);

create table refresh_token (
    id bigint generated by default as identity primary key,
    token_hash varchar(255) not null unique,
    family_id varchar(255) not null,
    user_id bigint not null,
    issued_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    used_at timestamp(6) with time zone,
    revoked_at timestamp(6) with time zone
);

create index idx_refresh_token_family on refresh_token (family_id);
